## set wallpaper 
wallpaper
#xmodmap .xmodmaprc 
##For evilwm
#xbindkeys 

## Window Managers.  
# Debian: awesome, dwm, evilwm, fvwm, i3, larswm, scrotwm, twm; #!: fluxbox, jwm, openbox, pekwm, ratpoison, wmii, xfce 

#exec awesome 
#exec dwm 
#exec evilwm -mask1 alt -snap 10 -nosoliddrag 
#exec fluxbox 
#exec fvwm
#exec i3
#exec icewm
#exec jwm
#exec larswm
exec openbox-session
#exec pekwm
#exec ratpoison
#exec scrotwm
#exec twm
#exec xfce4-session
