#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
xmodmap -e "remove lock = Caps_Lock"
xmodmap -e "add mod2 = Caps_Lock"
tint2 &
nm-applet &
conky -c ~/bin/pekconky &
feh --bg-fill ~/images/wallpapers/lonely_soul_by_werol.jpg
